#!/bin/bash
# run_session.sh — Orchestrate session with auto-evaluation loop
#
# Usage: ./scripts/run_session.sh <prompt-file>
#
# Flow:
# 1. Run main session (phase-by-phase with context isolation)
# 2. After completion, run session-evaluator
# 3. If evaluator finds issues, run fix-prompt-writer
# 4. If fix prompt generated, launch b-version
# 5. Write final report to docs/session_logs/session-NN-autoeval-report.md
#
# Each phase runs as a separate `claude -p` invocation, giving true
# context window isolation (not just /clear within a session).
#
# The prompt file should have phase markers: ## PHASE N
# Each phase runs with:
#   1. CLAUDE.md context (always loaded by Claude Code)
#   2. The specific phase instructions
#   3. A checkpoint file from the previous phase
#
# After each phase:
#   - Progress is written to a checkpoint file
#   - Git commit is expected (checked but not enforced)
#
# See: docs/HARNESS_DECISIONS.md HD-020

set -euo pipefail

# --- Argument Parsing ---

PROMPT_FILE="${1:?Usage: $0 <prompt-file>}"

if [ ! -f "$PROMPT_FILE" ]; then
    echo "Error: Prompt file not found: $PROMPT_FILE"
    exit 1
fi

# Extract session ID from the prompt filename (e.g., "70" from "session-70-prompt.md")
SESSION_ID=$(basename "$PROMPT_FILE" | grep -oE '[0-9]+[a-z]?' | head -1)
if [ -z "$SESSION_ID" ]; then
    echo "Error: Could not extract session ID from filename: $PROMPT_FILE"
    exit 1
fi

# --- Configuration ---

REPORT_FILE="docs/session_logs/session-${SESSION_ID}-autoeval-report.md"
CHECKPOINT_FILE=".claude/session_checkpoint.md"
B_PROMPT_FILE="docs/prompts/session-${SESSION_ID}b-prompt.md"
EVAL_OUTPUT_FILE="/tmp/session-${SESSION_ID}-eval-output.md"
FIX_OUTPUT_FILE="/tmp/session-${SESSION_ID}-fix-output.md"

# --- Helper Functions ---

timestamp() {
    date '+%Y-%m-%d %H:%M:%S'
}

log_stage() {
    local stage="$1"
    local status="$2"
    local ts
    ts=$(timestamp)
    echo "[$ts] [$stage] $status"
    echo "- **$stage** ($status): $ts" >> "$REPORT_FILE"
}

# --- Initialize Report ---

mkdir -p "$(dirname "$REPORT_FILE")"

cat > "$REPORT_FILE" << EOF
# Session ${SESSION_ID} Auto-Evaluation Report

Generated by \`scripts/run_session.sh\`

## Timeline
EOF

# --- Start ---

echo "=== Session Runner: Session $SESSION_ID ==="
echo "Prompt: $PROMPT_FILE"
echo "Session ID: $SESSION_ID"
echo "Report: $REPORT_FILE"
echo ""

log_stage "Session Start" "Initializing session $SESSION_ID"

# Set session tracking
echo "$SESSION_ID" > .claude/current_session.txt

# ============================================================
# STAGE 1: Run Main Session (phase-by-phase)
# ============================================================

log_stage "Main Session" "BEGIN"

# Split prompt into phases
# Accept both "## PHASE N" and "## Phase N:" markers
PHASE_PATTERN='^## [Pp][Hh][Aa][Ss][Ee] [0-9]'
PHASE_COUNT=$(grep -cE "$PHASE_PATTERN" "$PROMPT_FILE" || echo "0")
echo "Found $PHASE_COUNT phases"

if [ "$PHASE_COUNT" -eq 0 ]; then
    echo "No phase markers found. Running as single phase."
    log_stage "Single Phase" "BEGIN"
    if claude -p "$(cat "$PROMPT_FILE")"; then
        log_stage "Single Phase" "COMPLETE"
    else
        EXIT_CODE=$?
        log_stage "Single Phase" "FAILED (exit $EXIT_CODE)"
        echo ""
        echo "## Result" >> "$REPORT_FILE"
        echo "Main session failed at single phase. Skipping evaluation." >> "$REPORT_FILE"
        echo "Session failed. See $REPORT_FILE"
        exit $EXIT_CODE
    fi
else
    # Extract phase boundary line numbers into an array
    PHASE_LINES_STR=$(grep -nE "$PHASE_PATTERN" "$PROMPT_FILE" | cut -d: -f1)
    TOTAL_LINES=$(wc -l < "$PROMPT_FILE")

    # Convert to array for proper boundary calculation
    PHASE_LINES_ARRAY=()
    while IFS= read -r line; do
        PHASE_LINES_ARRAY+=("$line")
    done <<< "$PHASE_LINES_STR"

    PHASE_NUM=0
    PHASE_PASS=0
    PHASE_FAIL=0
    ARRAY_LEN=${#PHASE_LINES_ARRAY[@]}

    for ((i=0; i<ARRAY_LEN; i++)); do
        PHASE_NUM=$((PHASE_NUM + 1))
        LINE="${PHASE_LINES_ARRAY[$i]}"

        # End of this phase = start of next phase - 1, or end of file
        NEXT_IDX=$((i + 1))
        if [ "$NEXT_IDX" -lt "$ARRAY_LEN" ]; then
            END_LINE=$(( ${PHASE_LINES_ARRAY[$NEXT_IDX]} - 1 ))
        else
            END_LINE=$TOTAL_LINES
        fi

        echo ""
        echo "=== Phase $PHASE_NUM of $PHASE_COUNT (lines $LINE-$END_LINE) ==="
        log_stage "Phase $PHASE_NUM" "BEGIN"

        # Extract phase content
        PHASE_CONTENT=$(sed -n "${LINE},${END_LINE}p" "$PROMPT_FILE")

        # Build the phase prompt with context
        PHASE_PROMPT="You are running Phase $PHASE_NUM of $PHASE_COUNT in Session $SESSION_ID.

Read CLAUDE.md for project rules.
Read the session log at docs/session_logs/session-${SESSION_ID}-log.md for current progress.
$([ -f "$CHECKPOINT_FILE" ] && echo "Read $CHECKPOINT_FILE for previous phase results." || echo "This is the first phase.")

## Phase Instructions
$PHASE_CONTENT

## After completing this phase:
1. Update docs/session_logs/session-${SESSION_ID}-log.md — mark this phase done with what was built
2. Run tests: scripts/test-gate.sh fast
3. Commit changes with conventional commit message
4. Write a checkpoint summary to $CHECKPOINT_FILE with: what was done, key files changed, any issues found"

        # Run the phase
        echo "Running phase $PHASE_NUM..."
        if claude -p "$PHASE_PROMPT"; then
            log_stage "Phase $PHASE_NUM" "COMPLETE"
            PHASE_PASS=$((PHASE_PASS + 1))
        else
            EXIT_CODE=$?
            log_stage "Phase $PHASE_NUM" "FAILED (exit $EXIT_CODE)"
            PHASE_FAIL=$((PHASE_FAIL + 1))
            echo "Phase $PHASE_NUM FAILED (exit code $EXIT_CODE)."
            echo "Continuing to evaluation..."
            # Don't exit — let the evaluator assess what happened
            break
        fi

        # Check for commit
        LATEST_COMMIT=$(git log --oneline -1 --since="2 minutes ago" 2>/dev/null || echo "")
        if [ -n "$LATEST_COMMIT" ]; then
            echo "Commit: $LATEST_COMMIT"
        else
            echo "WARNING: No commit detected for phase $PHASE_NUM"
        fi
    done

    echo ""
    echo "=== Phase Execution Summary: $PHASE_PASS passed, $PHASE_FAIL failed out of $PHASE_COUNT ==="
fi

log_stage "Main Session" "END"

# ============================================================
# STAGE 2: Run Session Evaluator
# ============================================================

echo ""
echo "=== Running Session Evaluator ==="
log_stage "Evaluator" "BEGIN"

# Gather inputs for the evaluator
SESSION_LOG_CONTENT=""
if [ -f "SESSION_LOG.md" ]; then
    SESSION_LOG_CONTENT=$(cat SESSION_LOG.md)
fi

ASSESSMENT_CONTENT=""
ASSESSMENT_FILE="docs/assessments/session-${SESSION_ID}-assessment.md"
if [ -f "$ASSESSMENT_FILE" ]; then
    ASSESSMENT_CONTENT=$(cat "$ASSESSMENT_FILE")
else
    ASSESSMENT_CONTENT="No assessment found — this is itself a red flag."
fi

GIT_LOG_CONTENT=$(git log --oneline -20 2>/dev/null || echo "No git history available")

EVAL_PROMPT="You are the Rhodesli session evaluator. Read and evaluate session $SESSION_ID.

$(cat .claude/agents/session-evaluator.md)

---

## Session Inputs

### Original Prompt
$(cat "$PROMPT_FILE")

### Session Log
$SESSION_LOG_CONTENT

### Self-Assessment
$ASSESSMENT_CONTENT

### Recent Git History
$GIT_LOG_CONTENT

---

## Your Task
Produce your evaluation in the structured format specified above.
Be specific about evidence for each PASS/FAIL.
Categorize every concern as either B-Session (must fix) or Future Session (queue).
If there are NO b-session concerns, explicitly state: 'B-SESSION CONCERNS: NONE'
If there ARE b-session concerns, include the marker: 'B-SESSION CONCERNS: FOUND'"

echo "Invoking evaluator..."
if EVAL_OUTPUT=$(claude -p "$EVAL_PROMPT" 2>&1); then
    echo "$EVAL_OUTPUT" > "$EVAL_OUTPUT_FILE"
    log_stage "Evaluator" "COMPLETE"
    echo "Evaluator output saved to: $EVAL_OUTPUT_FILE"
else
    EXIT_CODE=$?
    echo "$EVAL_OUTPUT" > "$EVAL_OUTPUT_FILE"
    log_stage "Evaluator" "FAILED (exit $EXIT_CODE)"
    echo "Evaluator failed. Output saved to: $EVAL_OUTPUT_FILE"
    echo "Skipping fix-prompt-writer and b-version."
    # Append what we have to report and exit
    {
        echo ""
        echo "## Evaluator Output (partial)"
        echo '```'
        head -50 "$EVAL_OUTPUT_FILE" 2>/dev/null || echo "(empty)"
        echo '```'
        echo ""
        echo "## Result"
        echo "Evaluator failed. Manual review required."
    } >> "$REPORT_FILE"
    echo "Report written to: $REPORT_FILE"
    exit 1
fi

# Append evaluator output to report
{
    echo ""
    echo "## Evaluator Output"
    echo ""
    cat "$EVAL_OUTPUT_FILE"
    echo ""
} >> "$REPORT_FILE"

# ============================================================
# STAGE 3: Check for B-Session Concerns
# ============================================================

echo ""
echo "=== Checking Evaluator Results ==="

# Check for b-session concerns in evaluator output
HAS_B_SESSION_CONCERNS=false

if grep -qi 'B-SESSION CONCERNS: FOUND' "$EVAL_OUTPUT_FILE"; then
    HAS_B_SESSION_CONCERNS=true
elif grep -qi 'B-SESSION CONCERNS: NONE' "$EVAL_OUTPUT_FILE"; then
    HAS_B_SESSION_CONCERNS=false
else
    # Fallback: look for FAIL markers or b-session section with content
    if grep -qiE '(FAIL|must fix|b-session)' "$EVAL_OUTPUT_FILE"; then
        # Check if the b-session section has actual items (not just the header)
        B_SECTION=$(sed -n '/### B-Session/,/### Future Session\|## Metrics\|^$/p' "$EVAL_OUTPUT_FILE" | grep -cE '^[0-9]+\.' || echo "0")
        if [ "$B_SECTION" -gt 0 ]; then
            HAS_B_SESSION_CONCERNS=true
        fi
    fi
fi

if [ "$HAS_B_SESSION_CONCERNS" = false ]; then
    echo "No b-session concerns found. Session $SESSION_ID is clean."
    log_stage "B-Session Check" "CLEAN — no fixes needed"
    {
        echo ""
        echo "## Result"
        echo "Session $SESSION_ID: ALL CLEAR. No b-session fixes needed."
    } >> "$REPORT_FILE"
    echo ""
    echo "=== Session $SESSION_ID Complete ==="
    echo "Report: $REPORT_FILE"
    exit 0
fi

echo "B-session concerns found. Invoking fix-prompt-writer..."
log_stage "B-Session Check" "CONCERNS FOUND — generating fix prompt"

# ============================================================
# STAGE 4: Run Fix-Prompt-Writer
# ============================================================

echo ""
echo "=== Running Fix-Prompt-Writer ==="
log_stage "Fix-Prompt-Writer" "BEGIN"

FIX_PROMPT="You are the Rhodesli fix-prompt-writer. Generate a b-session prompt for session ${SESSION_ID}.

$(cat .claude/agents/fix-prompt-writer.md)

---

## Evaluator Output
$(cat "$EVAL_OUTPUT_FILE")

## Original Session Prompt
$(cat "$PROMPT_FILE")

---

## Your Task
Write a focused b-session prompt that addresses ONLY the b-session concerns.
Output the complete prompt content — it will be saved to: $B_PROMPT_FILE
Do NOT include any commentary outside the prompt itself."

echo "Invoking fix-prompt-writer..."
if FIX_OUTPUT=$(claude -p "$FIX_PROMPT" 2>&1); then
    echo "$FIX_OUTPUT" > "$FIX_OUTPUT_FILE"
    # Save the fix prompt to the canonical location
    mkdir -p "$(dirname "$B_PROMPT_FILE")"
    cp "$FIX_OUTPUT_FILE" "$B_PROMPT_FILE"
    log_stage "Fix-Prompt-Writer" "COMPLETE — saved to $B_PROMPT_FILE"
    echo "Fix prompt saved to: $B_PROMPT_FILE"
else
    EXIT_CODE=$?
    echo "$FIX_OUTPUT" > "$FIX_OUTPUT_FILE"
    log_stage "Fix-Prompt-Writer" "FAILED (exit $EXIT_CODE)"
    echo "Fix-prompt-writer failed. Manual b-session prompt needed."
    {
        echo ""
        echo "## Fix-Prompt-Writer Output (partial)"
        echo '```'
        head -50 "$FIX_OUTPUT_FILE" 2>/dev/null || echo "(empty)"
        echo '```'
        echo ""
        echo "## Result"
        echo "Fix-prompt-writer failed. Manual review required."
        echo "Evaluator concerns are logged above — write b-session prompt manually."
    } >> "$REPORT_FILE"
    echo "Report written to: $REPORT_FILE"
    exit 1
fi

# Append fix-prompt-writer output to report
{
    echo ""
    echo "## Fix-Prompt-Writer Output"
    echo "Saved to: \`$B_PROMPT_FILE\`"
    echo ""
    echo "<details>"
    echo "<summary>Generated b-session prompt</summary>"
    echo ""
    cat "$B_PROMPT_FILE"
    echo ""
    echo "</details>"
    echo ""
} >> "$REPORT_FILE"

# ============================================================
# STAGE 5: Launch B-Version Session
# ============================================================

echo ""
echo "=== Launching B-Version Session ==="
log_stage "B-Version" "BEGIN"

echo "Running session ${SESSION_ID}b from: $B_PROMPT_FILE"

if claude -p "$(cat "$B_PROMPT_FILE")"; then
    log_stage "B-Version" "COMPLETE"
    echo "B-version session completed."
else
    EXIT_CODE=$?
    log_stage "B-Version" "FAILED (exit $EXIT_CODE)"
    echo "B-version session failed (exit code $EXIT_CODE)."
    {
        echo ""
        echo "## Result"
        echo "B-version session FAILED (exit $EXIT_CODE). Manual intervention required."
    } >> "$REPORT_FILE"
    echo "Report written to: $REPORT_FILE"
    exit $EXIT_CODE
fi

# ============================================================
# STAGE 6: Final Report
# ============================================================

echo ""
echo "=== Generating Final Report ==="

# Get final git state
FINAL_GIT_LOG=$(git log --oneline -5 2>/dev/null || echo "No git history")
FINAL_TEST_COUNT=""
if [ -f "venv/bin/activate" ]; then
    FINAL_TEST_COUNT=$(source venv/bin/activate && pytest tests/ -x -q --tb=no 2>&1 | tail -1 || echo "Tests unavailable")
fi

{
    echo ""
    echo "## Final State"
    echo ""
    echo "### Recent Commits"
    echo '```'
    echo "$FINAL_GIT_LOG"
    echo '```'
    echo ""
    if [ -n "$FINAL_TEST_COUNT" ]; then
        echo "### Test Results"
        echo '```'
        echo "$FINAL_TEST_COUNT"
        echo '```'
        echo ""
    fi
    echo "## Result"
    echo "Session $SESSION_ID + b-version: COMPLETE."
    echo "Review this report and the b-version prompt at \`$B_PROMPT_FILE\`."
} >> "$REPORT_FILE"

log_stage "Session End" "COMPLETE"

echo ""
echo "=== Session $SESSION_ID + B-Version Complete ==="
echo "Full report: $REPORT_FILE"
echo "B-version prompt: $B_PROMPT_FILE"
